name: GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: cachix/install-nix-action@v18

    - uses: cachix/cachix-action@v12
      with:
        name: gvolpe-nixos
        authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

    - name: "Build docs"
      run: |
        mkdir public
        nix build .#docs-search
        cat result > public/search.html
        nix build .#docs
        cp -r result/share/doc/neovim-flake/* public

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
